# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationID', models.CharField(max_length=32)),
                ('TypeID', models.CharField(max_length=32)),
                ('PicUrl', models.CharField(max_length=500)),
                ('Remark', models.CharField(blank=True, max_length=500)),
                ('Status', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '单位资质',
            },
        ),
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IID', models.CharField(max_length=32)),
                ('Name', models.CharField(max_length=200)),
                ('Remark', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': '资质类别',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IID', models.CharField(max_length=32, unique=True, verbose_name='IID')),
                ('Name', models.CharField(max_length=200, verbose_name='机构名称')),
                ('CreditNumber', models.CharField(blank=True, max_length=32, verbose_name='机构代码')),
                ('LegalRepresentative', models.CharField(blank=True, max_length=32, verbose_name='法人代表')),
                ('RegisteredCapital', models.IntegerField(default=0, verbose_name='注册资金')),
                ('BusinessScope', models.CharField(blank=True, max_length=200, verbose_name='经营范围')),
                ('FoundedDate', models.DateField(default='1970-1-1', verbose_name='成立时间')),
                ('BusinessTerm', models.DateField(default='1970-1-1', verbose_name='经营期限')),
                ('LogoURL', models.ImageField(blank=True, upload_to='upload', verbose_name='LOGO')),
                ('WebSiteURL', models.URLField(blank=True, verbose_name='网站')),
                ('Address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('Country', models.CharField(blank=True, max_length=200, verbose_name='国家')),
                ('Province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('City', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('District', models.CharField(blank=True, max_length=50, verbose_name='区域')),
                ('Location', models.CharField(blank=True, max_length=50, verbose_name='经纬度')),
                ('Contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('EMail', models.CharField(blank=True, max_length=100, verbose_name='电子邮件')),
                ('TelPhone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('QQ', models.CharField(blank=True, max_length=20, verbose_name='QQ')),
                ('WeiXin', models.CharField(blank=True, max_length=50, verbose_name='微信')),
                ('WeiXinPublic', models.CharField(blank=True, max_length=100, verbose_name='微信公众号')),
                ('WangWang', models.CharField(blank=True, max_length=50, verbose_name='旺旺')),
                ('DingDing', models.CharField(blank=True, max_length=50, verbose_name='钉钉')),
                ('ZipCode', models.CharField(blank=True, max_length=10, verbose_name='邮编')),
                ('Profile', models.CharField(blank=True, max_length=2000, verbose_name='简介')),
                ('Grade', models.FloatField(default=0, verbose_name='评分')),
                ('Level', models.IntegerField(default=0, verbose_name='等级')),
                ('CreateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Status', models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (-1, '审核未通过')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '单位基本资料',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IID', models.CharField(max_length=32, unique=True, verbose_name='IID')),
                ('Name', models.CharField(max_length=200, verbose_name='类型名称')),
                ('Remark', models.CharField(max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '单位类型',
            },
        ),
        migrations.AddField(
            model_name='info',
            name='Type',
            field=models.ForeignKey(blank=True, on_delete='id', to='Organization.Type', to_field='IID'),
        ),
    ]
