# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='OrganizationID',
        ),
        migrations.AddField(
            model_name='info',
            name='Organization',
            field=models.ForeignKey(default=1498622403.639829, on_delete='id', to='Organization.Info', to_field='IID'),
        ),
    ]
