# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20170628_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='OrganizationName',
            new_name='FromName',
        ),
        migrations.AlterField(
            model_name='info',
            name='Organization',
            field=models.ForeignKey(default=1498628402.206771, on_delete='id', to='Organization.Info', to_field='IID'),
        ),
    ]
