# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20170628_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='IID',
            field=models.CharField(max_length=32, unique=True, verbose_name='IID'),
        ),
        migrations.AlterField(
            model_name='info',
            name='Organization',
            field=models.ForeignKey(default=1498628545.64833, on_delete='id', to='Organization.Info', to_field='IID'),
        ),
    ]
