# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20170628_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Organization',
        ),
        migrations.AlterField(
            model_name='info',
            name='FromName',
            field=models.CharField(max_length=100, verbose_name='公司／个人名称'),
        ),
    ]
