# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_auto_20170628_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='info',
            name='Telphone',
            field=models.CharField(blank=True, max_length=50, verbose_name='联系电话'),
        ),
    ]
