# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IID', models.CharField(max_length=32, unique=True, verbose_name='IID')),
                ('Name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('Charset', models.CharField(choices=[('UTF-8', 'UTF-8'), ('GB2312', 'GB2312')], default='UTF-8', max_length=10, verbose_name='编码')),
                ('InURLRegularExpression', models.CharField(max_length=100, verbose_name='入口列表页')),
                ('InURLNumber', models.IntegerField(default=1, verbose_name='页面数')),
                ('PageProperty', models.CharField(max_length=100, verbose_name='属性名')),
                ('PagePropertyRegularExpression', models.CharField(max_length=100, verbose_name='属性内容匹配')),
                ('BodyFilterTextRegularExpression', models.CharField(max_length=5000, verbose_name='属性名')),
                ('TextReplace', models.CharField(max_length=5000, verbose_name='替换文本')),
                ('WorkInterval', models.IntegerField(default=300, verbose_name='页面数')),
                ('ThreadNumber', models.IntegerField(default=300, verbose_name='页面数')),
                ('DatabaseConnectStr', models.CharField(max_length=5000, verbose_name='数据库连接')),
                ('Status', models.IntegerField(choices=[(0, '停止'), (1, '启用')], default=0, verbose_name='状态')),
            ],
        ),
    ]
