# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chong', '0002_auto_20170630_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ResponseFormat',
            field=models.CharField(choices=[('XML', 'HTML/XML'), ('JSON', 'JSON')], default='XML', max_length=10, verbose_name='返回格式'),
        ),
        migrations.AlterField(
            model_name='task',
            name='EnableBroswer',
            field=models.IntegerField(choices=[(0, '关闭'), (1, '启用')], default=0, verbose_name='无头浏览器'),
        ),
    ]
