# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chong', '0004_auto_20170701_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Account',
            field=models.CharField(blank=True, max_length=100, verbose_name='账号,密码'),
        ),
    ]
