# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chong', '0005_auto_20170701_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='SpiderName',
            field=models.CharField(default='', max_length=20, verbose_name='爬虫名称'),
        ),
    ]
