# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chong', '0008_task_starturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='CategoryID',
            field=models.CharField(blank=True, max_length=100, verbose_name='类别'),
        ),
    ]
