# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chong', '0009_task_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='InURLNumber',
        ),
        migrations.RemoveField(
            model_name='task',
            name='InURLRegularExpression',
        ),
        migrations.RemoveField(
            model_name='task',
            name='PageProperty',
        ),
        migrations.AddField(
            model_name='task',
            name='DataPersistenceType',
            field=models.CharField(choices=[('POST', 'POST提交保存'), ('MYSQL', 'MYSQL保存')], default='POST', max_length=10, verbose_name='保存方式'),
        ),
        migrations.AddField(
            model_name='task',
            name='DownLoadImg',
            field=models.IntegerField(choices=[(0, '不下载'), (1, '下载')], default=0, verbose_name='下载图片'),
        ),
        migrations.AddField(
            model_name='task',
            name='ListURLRegularExpression',
            field=models.CharField(blank=True, max_length=100, verbose_name='分页列表链接规则'),
        ),
        migrations.AddField(
            model_name='task',
            name='PageURLRegularExpression',
            field=models.CharField(default='', max_length=100, verbose_name='详情列表规则'),
        ),
        migrations.AddField(
            model_name='task',
            name='PostURL',
            field=models.CharField(blank=True, max_length=200, verbose_name='POST接收地址'),
        ),
        migrations.AlterField(
            model_name='task',
            name='BodyFilterTextRegularExpression',
            field=models.CharField(max_length=5000, verbose_name='正文过滤规则'),
        ),
        migrations.AlterField(
            model_name='task',
            name='DatabaseConnectStr',
            field=models.CharField(blank=True, max_length=5000, verbose_name='数据库连接'),
        ),
        migrations.AlterField(
            model_name='task',
            name='StartURL',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='起始页'),
        ),
    ]
