# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chong', '0011_auto_20170718_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='PageListRegularExpression',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='详情页列表规则'),
        ),
        migrations.AlterField(
            model_name='task',
            name='PageURLRegularExpression',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='详情页链接规则'),
        ),
    ]
