# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chong', '0013_auto_20170718_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='WPPassword',
            field=models.CharField(blank=True, max_length=200, verbose_name='WP密码'),
        ),
        migrations.AddField(
            model_name='task',
            name='WPUserName',
            field=models.CharField(blank=True, max_length=200, verbose_name='WP账号'),
        ),
        migrations.AlterField(
            model_name='task',
            name='DataPersistenceType',
            field=models.CharField(choices=[('WPRPC', 'WordPress xmlrpc'), ('POST', 'POST提交保存'), ('MYSQL', 'MYSQL保存')], default='POST', max_length=10, verbose_name='保存方式'),
        ),
        migrations.AlterField(
            model_name='task',
            name='PostURL',
            field=models.CharField(blank=True, max_length=200, verbose_name='POST／RPC URL'),
        ),
    ]
